### PR TITLE
update page title and favicon

### PR DESCRIPTION
**Pull request by ri-tae-ka**
Updated favicon and added page title.
Screenshot 2021-07-16 141455

### CODE REVIEW

**Comment by ri-tae-ka** [comment]
@Ananya02850 is this project under any Open Source Program?

**Comment by Ananya02850** [comment]
yes

**Comment by ri-tae-ka** [comment]
> yes

If so please do label the PR under the applicable Program.
@Ananya02850

**Comment by Ananya02850** [comment]
it's already done ✔

**Pull request merged**
